# CI项目
name: OWRT-x86

# CI计划
on:
  # 自动编译：当Auto-Clean运行完成后
  workflow_run:
    workflows: ["Auto-Clean"]
    types:
      - completed
  # 手动编译
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: '手动调整插件包，仅限一个。'
        required: false
        type: string
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: 'false'
        required: false
        type: boolean

# CI权限
permissions:
  contents: write
  actions: write

# CI任务
jobs:
  config:
    name: ${{matrix.TARGET}}
    strategy:
      fail-fast: false
      matrix:
        TARGET: [X86]
        SOURCE: [immortalwrt/immortalwrt]

    # 调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      # 编译平台
      WRT_TARGET: ${{matrix.TARGET}}
      # 默认主题
      WRT_THEME: argon
      # 默认主机名
      WRT_NAME: SimWRT
      # 默认WIFI名
      WRT_WIFI: SimWRT
      # 默认地址
      WRT_IP: 10.10.10.23
      # 源码链接
      WRT_REPO: https://github.com/${{matrix.SOURCE}}.git
      # 源码分支
      WRT_BRANCH: ${{ inputs.BRANCH || 'master' }}
      # 源码名称
      WRT_SOURCE: ${{matrix.SOURCE}}
      # 插件调整
      WRT_PACKAGE: ${{ inputs.PACKAGE }}
      # 仅输出配置文件
      WRT_TEST: ${{ inputs.TEST }}

